/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.bars_register.forms;

import br.com.bars_register.util.View;
import java.awt.Color;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author limag
 */
public class Produtos extends javax.swing.JFrame {

    /**
     * Creates new form Produtos
     */
    public Produtos() {
        initComponents();
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color(0x4E342E));

        for (int i = 0; i < TblProdutos.getModel().getColumnCount(); i++) {
            TblProdutos.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMain = new javax.swing.JPanel();
        PanelFundo = new javax.swing.JPanel();
        txtBuscaProduto = new javax.swing.JTextField();
        BtnNovoProduto = new javax.swing.JButton();
        JsPanelTabelaProdutos = new javax.swing.JScrollPane();
        TblProdutos = new javax.swing.JTable();
        BtnExcluir = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelMain.setBackground(new java.awt.Color(233, 236, 239));
        PanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFundo.setBackground(new java.awt.Color(255, 255, 255));
        View.standardCornerRadius(PanelFundo);
        PanelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscaProduto.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        PanelFundo.add(txtBuscaProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 256, 40));
        View.standardCornerRadius(txtBuscaProduto);

        BtnNovoProduto.setBackground(new java.awt.Color(93, 64, 55));
        BtnNovoProduto.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        BtnNovoProduto.setForeground(new java.awt.Color(255, 255, 255));
        BtnNovoProduto.setText("+Novo Produto");
        BtnNovoProduto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PanelFundo.add(BtnNovoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 120, 40));
        View.standardCornerRadius(BtnNovoProduto);

        View.standardCornerRadius(JsPanelTabelaProdutos);

        TblProdutos.setBackground(new java.awt.Color(248, 249, 250));
        TblProdutos.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        TblProdutos.setForeground(new java.awt.Color(255, 255, 255));
        TblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Preço", "Estoque", "Ações"
            }
        ));
        TblProdutos.setGridColor(new java.awt.Color(78, 52, 46));
        TblProdutos.setShowGrid(false);
        JsPanelTabelaProdutos.setViewportView(TblProdutos);

        PanelFundo.add(JsPanelTabelaProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 610, 380));

        PanelMain.add(PanelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 649, 465));

        BtnExcluir.setBackground(new java.awt.Color(78, 52, 46));
        BtnExcluir.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        BtnExcluir.setForeground(new java.awt.Color(255, 0, 0));
        BtnExcluir.setText("Excluir");
        PanelMain.add(BtnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 495, 120, 40));
        View.standardCornerRadius(BtnExcluir);

        BtnEditar.setBackground(new java.awt.Color(78, 52, 46));
        BtnEditar.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        BtnEditar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEditar.setText("Editar");
        PanelMain.add(BtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 495, 120, 40));
        View.standardCornerRadius(BtnEditar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produtos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnNovoProduto;
    private javax.swing.JScrollPane JsPanelTabelaProdutos;
    private javax.swing.JPanel PanelFundo;
    private javax.swing.JPanel PanelMain;
    private javax.swing.JTable TblProdutos;
    private javax.swing.JTextField txtBuscaProduto;
    // End of variables declaration//GEN-END:variables
}
