/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.bars_register.view.forms;

import br.com.bars_register.DAOClasses.FornecedorDAO;
import br.com.bars_register.persistence.Fornecedor;
import br.com.bars_register.util.View;
import br.com.bars_register.view.register.RegistroFornecedores;
import com.formdev.flatlaf.FlatClientProperties;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author limag
 */
public class Fornecedores extends javax.swing.JFrame {

    /**
     * Creates new form Fornecedores
     */
    public Fornecedores() {
        initComponents();
        txtBuscaFornecedor.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Busque um Fornecedor");
        atualizarTabelaFornecedores();
        listnerTabela();
    }

    public void atualizarTabelaFornecedores() {
        FornecedorDAO dao = new FornecedorDAO();
        String nome = txtBuscaFornecedor.getText();
        List<Fornecedor> listaFornecedores = dao.listarFornecedores(nome);

        DefaultTableModel modeloTable = (DefaultTableModel) TblFornecedores.getModel();
        modeloTable.setRowCount(0);

        for (Fornecedor fornecedor : listaFornecedores) {
            Object[] rowData = {
                fornecedor.getNome(),
                fornecedor.getContato(),
                fornecedor.getEndereco(),
                fornecedor.getCnpj()
            };
            modeloTable.addRow(rowData);
        }
    }
    
        public void atualizarTotalFornecedores() {
        FornecedorDAO dao = new FornecedorDAO();
        int total = dao.listarFornecedores(txtBuscaFornecedor.getText()).size();
        

        LbTotalFornecedoresNumero.setText(String.valueOf(total));
    }

    /**
     * Verifica se há uma row selecionada para ativar ou não o botão de excluir
     */
    private void listnerTabela() {
        TblFornecedores.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selecionado = TblFornecedores.getSelectedRow();
                if (selecionado != -1) {
                    BtnExcluir.setEnabled(true);
                    BtnEditar.setEnabled(true);
                } else {
                    BtnExcluir.setEnabled(false);
                    BtnEditar.setEnabled(false);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMain = new javax.swing.JPanel();
        PanelFundo = new javax.swing.JPanel();
        BtnNovoFornecedor = new javax.swing.JButton();
        txtBuscaFornecedor = new javax.swing.JTextField();
        PanelTotalFornecedores = new javax.swing.JPanel();
        LbTotalFornecedores = new javax.swing.JLabel();
        LbTotalFornecedoresNumero = new javax.swing.JLabel();
        JsPanelTabelaFornecedores = new javax.swing.JScrollPane();
        TblFornecedores = new javax.swing.JTable();
        BtnExcluir = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelMain.setBackground(new java.awt.Color(233, 236, 239));

        PanelFundo.setBackground(new java.awt.Color(255, 255, 255));
        View.standardCornerRadius(PanelFundo);

        BtnNovoFornecedor.setBackground(new java.awt.Color(78, 52, 46));
        BtnNovoFornecedor.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        BtnNovoFornecedor.setForeground(new java.awt.Color(255, 255, 255));
        BtnNovoFornecedor.setText("+Novo Fornecedor");
        View.standardCornerRadius(BtnNovoFornecedor);
        BtnNovoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoFornecedorActionPerformed(evt);
            }
        });

        txtBuscaFornecedor.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtBuscaFornecedorCaretUpdate(evt);
            }
        });
        View.standardCornerRadius(txtBuscaFornecedor);

        PanelTotalFornecedores.setBackground(new java.awt.Color(78, 52, 46));
        PanelTotalFornecedores.setPreferredSize(new java.awt.Dimension(180, 100));
        View.standardCornerRadius(PanelTotalFornecedores);

        LbTotalFornecedores.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        LbTotalFornecedores.setForeground(new java.awt.Color(173, 181, 189));
        LbTotalFornecedores.setText("Total de Fornecedores");

        LbTotalFornecedoresNumero.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        LbTotalFornecedoresNumero.setForeground(new java.awt.Color(255, 255, 255));
        LbTotalFornecedoresNumero.setText("0");

        javax.swing.GroupLayout PanelTotalFornecedoresLayout = new javax.swing.GroupLayout(PanelTotalFornecedores);
        PanelTotalFornecedores.setLayout(PanelTotalFornecedoresLayout);
        PanelTotalFornecedoresLayout.setHorizontalGroup(
            PanelTotalFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTotalFornecedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTotalFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LbTotalFornecedoresNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LbTotalFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        PanelTotalFornecedoresLayout.setVerticalGroup(
            PanelTotalFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTotalFornecedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbTotalFornecedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbTotalFornecedoresNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        View.standardCornerRadius(JsPanelTabelaFornecedores);

        TblFornecedores.setBackground(new java.awt.Color(248, 249, 250));
        TblFornecedores.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        TblFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Contato", "Endereço", "CNPJ"
            }
        ));
        TblFornecedores.setGridColor(new java.awt.Color(78, 52, 46));
        TblFornecedores.setShowGrid(false);
        JsPanelTabelaFornecedores.setViewportView(TblFornecedores);

        javax.swing.GroupLayout PanelFundoLayout = new javax.swing.GroupLayout(PanelFundo);
        PanelFundo.setLayout(PanelFundoLayout);
        PanelFundoLayout.setHorizontalGroup(
            PanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFundoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelFundoLayout.createSequentialGroup()
                        .addComponent(txtBuscaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202)
                        .addComponent(BtnNovoFornecedor))
                    .addGroup(PanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelTotalFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JsPanelTabelaFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        PanelFundoLayout.setVerticalGroup(
            PanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFundoLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(PanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnNovoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(PanelTotalFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JsPanelTabelaFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        BtnExcluir.setBackground(new java.awt.Color(78, 52, 46));
        BtnExcluir.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        BtnExcluir.setForeground(new java.awt.Color(255, 0, 0));
        BtnExcluir.setText("Excluir");
        BtnExcluir.setEnabled(false);
        View.standardCornerRadius(BtnExcluir);
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        BtnEditar.setBackground(new java.awt.Color(78, 52, 46));
        BtnEditar.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        BtnEditar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEditar.setText("Editar");
        BtnEditar.setEnabled(false);
        View.standardCornerRadius(BtnEditar);
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMainLayout = new javax.swing.GroupLayout(PanelMain);
        PanelMain.setLayout(PanelMainLayout);
        PanelMainLayout.setHorizontalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelMainLayout.createSequentialGroup()
                        .addComponent(BtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(BtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        PanelMainLayout.setVerticalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(PanelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNovoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoFornecedorActionPerformed
        RegistroFornecedores registroFornecedores = new RegistroFornecedores(this);
        registroFornecedores.setVisible(true);
    }//GEN-LAST:event_BtnNovoFornecedorActionPerformed

    private void txtBuscaFornecedorCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtBuscaFornecedorCaretUpdate
        atualizarTabelaFornecedores();
    }//GEN-LAST:event_txtBuscaFornecedorCaretUpdate

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        RegistroFornecedores registroFornecedores = new RegistroFornecedores(this);
        registroFornecedores.setVisible(true);

        int selectedRow = TblFornecedores.getSelectedRow();
        String nome = TblFornecedores.getValueAt(selectedRow, 0).toString();
        String contato = TblFornecedores.getValueAt(selectedRow, 1).toString();
        String endereco = TblFornecedores.getValueAt(selectedRow, 2).toString();
        String cnpj = TblFornecedores.getValueAt(selectedRow, 3).toString();
        
        registroFornecedores.setDadosFornecedor(nome, contato, endereco, cnpj);
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {
        int rowSelecionada = TblFornecedores.getSelectedRow();
        String cnpj = TblFornecedores.getValueAt(rowSelecionada, 3).toString();
        String nome = TblFornecedores.getValueAt(rowSelecionada, 0).toString();
        
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Deseja excluir o fornecedor " + nome + "?",
            "Confirmar Exclusão",
            javax.swing.JOptionPane.YES_NO_OPTION
        );
        
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            FornecedorDAO dao = new FornecedorDAO();
            dao.excluirFornecedor(cnpj);
            atualizarTabelaFornecedores();
        }
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fornecedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnNovoFornecedor;
    private javax.swing.JScrollPane JsPanelTabelaFornecedores;
    private javax.swing.JLabel LbTotalFornecedores;
    private javax.swing.JLabel LbTotalFornecedoresNumero;
    private javax.swing.JPanel PanelFundo;
    private javax.swing.JPanel PanelMain;
    private javax.swing.JPanel PanelTotalFornecedores;
    private javax.swing.JTable TblFornecedores;
    private javax.swing.JTextField txtBuscaFornecedor;
    // End of variables declaration//GEN-END:variables
}
