/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.bars_register.view.forms;

import br.com.bars_register.DAOClasses.ProdutoDAO;
import br.com.bars_register.persistence.Produto;
import br.com.bars_register.util.View;
import br.com.bars_register.view.register.RegistroProdutos;
import com.formdev.flatlaf.FlatClientProperties;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author limag
 */
public class Produtos extends javax.swing.JFrame {

    /**
     * Creates new form Produtos
     */
    public Produtos() {
        initComponents();
        atualizarTabelaProdutos();
        txtBuscaProduto.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Busque um produto");
        listnerTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMain = new javax.swing.JPanel();
        PanelFundo = new javax.swing.JPanel();
        txtBuscaProduto = new javax.swing.JTextField();
        BtnNovoProduto = new javax.swing.JButton();
        JsPanelTabelaProdutos = new javax.swing.JScrollPane();
        TblProdutos = new javax.swing.JTable();
        BtnExcluir = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelMain.setBackground(new java.awt.Color(233, 236, 239));
        PanelMain.setPreferredSize(new java.awt.Dimension(670, 540));
        PanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFundo.setBackground(new java.awt.Color(255, 255, 255));
        View.standardCornerRadius(PanelFundo);
        PanelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscaProduto.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtBuscaProduto.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtBuscaProdutoCaretUpdate(evt);
            }
        });
        PanelFundo.add(txtBuscaProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 256, 40));
        View.standardCornerRadius(txtBuscaProduto);

        BtnNovoProduto.setBackground(new java.awt.Color(93, 64, 55));
        BtnNovoProduto.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        BtnNovoProduto.setForeground(new java.awt.Color(255, 255, 255));
        BtnNovoProduto.setText("+Novo Produto");
        BtnNovoProduto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoProdutoActionPerformed(evt);
            }
        });
        PanelFundo.add(BtnNovoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 120, 40));
        View.standardCornerRadius(BtnNovoProduto);

        View.standardCornerRadius(JsPanelTabelaProdutos);

        TblProdutos.setBackground(new java.awt.Color(248, 249, 250));
        TblProdutos.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        TblProdutos.setForeground(new java.awt.Color(0, 0, 0));
        TblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Preço", "Estoque", "Ações"
            }
        ));
        TblProdutos.setGridColor(new java.awt.Color(78, 52, 46));
        TblProdutos.setShowGrid(false);
        JsPanelTabelaProdutos.setViewportView(TblProdutos);

        PanelFundo.add(JsPanelTabelaProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 610, 380));

        PanelMain.add(PanelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 649, 465));

        BtnExcluir.setBackground(new java.awt.Color(78, 52, 46));
        BtnExcluir.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        BtnExcluir.setForeground(new java.awt.Color(255, 0, 0));
        BtnExcluir.setText("Excluir");
        BtnExcluir.setEnabled(false);
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });
        PanelMain.add(BtnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 495, 120, 40));
        View.standardCornerRadius(BtnExcluir);

        BtnEditar.setBackground(new java.awt.Color(78, 52, 46));
        BtnEditar.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        BtnEditar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEditar.setText("Editar");
        BtnEditar.setEnabled(false);
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });
        PanelMain.add(BtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 495, 120, 40));
        View.standardCornerRadius(BtnEditar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoProdutoActionPerformed
        RegistroProdutos registroProdutos = new RegistroProdutos(this);
        registroProdutos.setVisible(true);

    }//GEN-LAST:event_BtnNovoProdutoActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        try {
            ProdutoDAO dao = new ProdutoDAO();
            int rowSelecionada = TblProdutos.getSelectedRow();

            String nome = TblProdutos.getValueAt(rowSelecionada, 0).toString();
            int confirm = javax.swing.JOptionPane.showConfirmDialog(
                    this,
                    "Deseja excluir o produto " + nome + "?",
                    "Confirmar Exclusão",
                    javax.swing.JOptionPane.YES_NO_OPTION
            );
            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                dao.excluirProduto(nome);
                atualizarTabelaProdutos();
                JOptionPane.showMessageDialog(this, "Produto " + nome + " deletado!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void txtBuscaProdutoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtBuscaProdutoCaretUpdate
        atualizarTabelaProdutos();
    }//GEN-LAST:event_txtBuscaProdutoCaretUpdate

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        RegistroProdutos registroProdutos = new RegistroProdutos(this);
        registroProdutos.setVisible(true);

        int selectedRow = TblProdutos.getSelectedRow();
        String nome = TblProdutos.getValueAt(selectedRow, 0).toString();
        String preco = TblProdutos.getValueAt(selectedRow, 1).toString().replace("R$ ", "");
        String estoque = TblProdutos.getValueAt(selectedRow, 2).toString();
        String acoes = TblProdutos.getValueAt(selectedRow, 3).toString();
        registroProdutos.setDadosProduto(nome, preco, estoque, acoes);

    }//GEN-LAST:event_BtnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produtos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnNovoProduto;
    private javax.swing.JScrollPane JsPanelTabelaProdutos;
    private javax.swing.JPanel PanelFundo;
    private javax.swing.JPanel PanelMain;
    private javax.swing.JTable TblProdutos;
    private javax.swing.JTextField txtBuscaProduto;
    // End of variables declaration//GEN-END:variables

    public void atualizarTabelaProdutos() {
        ProdutoDAO produtoDAO = new ProdutoDAO();
        String nomeProduto = txtBuscaProduto.getText();

        List<Produto> listaProdutos = produtoDAO.listarProdutos(nomeProduto);

        DefaultTableModel modeloTable = (DefaultTableModel) TblProdutos.getModel();
        modeloTable.setRowCount(0);

        for (Produto produto : listaProdutos) {
            Object[] rowData = {
                produto.getNome(),
                "R$ " + produto.getPreco(),
                produto.getEstoque(),
                produto.getAcoes()
            };
            modeloTable.addRow(rowData);
        }
    }

    /**
     * Verifica se há uma row selecionada para ativar ou não o botão de excluir
     */
    private void listnerTabela() {
        TblProdutos.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selecionado = TblProdutos.getSelectedRow();
                if (selecionado != -1) {
                    BtnExcluir.setEnabled(true);
                    BtnEditar.setEnabled(true);
                } else {
                    BtnExcluir.setEnabled(false);
                    BtnEditar.setEnabled(false);
                }
            }
        });
    }
}
