/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.bars_register.view.forms;

import br.com.bars_register.DAOClasses.VendaDAO;
import br.com.bars_register.persistence.Relatorio;
import br.com.bars_register.persistence.Usuario;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import br.com.bars_register.util.View;

/**
 *
 * @author limag
 */
public class Relatorios extends javax.swing.JFrame {

    /**
     * Creates new form Relatorio
     */
    private Usuario usuario;

    public Relatorios(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMain = new javax.swing.JPanel();
        PanelFundo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaRelatorio = new javax.swing.JTextArea();
        PanelReceita = new javax.swing.JPanel();
        LbReceitaTotal = new javax.swing.JLabel();
        LbReceitaNumero = new javax.swing.JLabel();
        PanelTotalVenda = new javax.swing.JPanel();
        LbTotalVendas = new javax.swing.JLabel();
        LbVendasNumero = new javax.swing.JLabel();
        PanelDataEBotao = new javax.swing.JPanel();
        txtDataFinal = new javax.swing.JFormattedTextField();
        txtDataInicial = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnGerar = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelMain.setBackground(new java.awt.Color(233, 236, 239));

        PanelFundo.setBackground(new java.awt.Color(255, 255, 255));
        View.standardCornerRadius(PanelFundo);

        txtAreaRelatorio.setColumns(20);
        txtAreaRelatorio.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtAreaRelatorio.setRows(5);
        txtAreaRelatorio.setBorder(null);
        jScrollPane1.setViewportView(txtAreaRelatorio);

        javax.swing.GroupLayout PanelFundoLayout = new javax.swing.GroupLayout(PanelFundo);
        PanelFundo.setLayout(PanelFundoLayout);
        PanelFundoLayout.setHorizontalGroup(
            PanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        PanelFundoLayout.setVerticalGroup(
            PanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );

        PanelReceita.setBackground(new java.awt.Color(78, 52, 46));
        PanelReceita.setPreferredSize(new java.awt.Dimension(180, 100));
        View.standardCornerRadius(PanelReceita);

        LbReceitaTotal.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        LbReceitaTotal.setForeground(new java.awt.Color(173, 181, 189));
        LbReceitaTotal.setText("Receita Total");

        LbReceitaNumero.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        LbReceitaNumero.setForeground(new java.awt.Color(255, 255, 255));
        LbReceitaNumero.setText("R$ 0,00");

        javax.swing.GroupLayout PanelReceitaLayout = new javax.swing.GroupLayout(PanelReceita);
        PanelReceita.setLayout(PanelReceitaLayout);
        PanelReceitaLayout.setHorizontalGroup(
            PanelReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReceitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbReceitaNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addGroup(PanelReceitaLayout.createSequentialGroup()
                        .addComponent(LbReceitaTotal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelReceitaLayout.setVerticalGroup(
            PanelReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReceitaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(LbReceitaTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbReceitaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        PanelTotalVenda.setBackground(new java.awt.Color(78, 52, 46));
        PanelTotalVenda.setPreferredSize(new java.awt.Dimension(180, 100));
        View.standardCornerRadius(PanelTotalVenda);

        LbTotalVendas.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        LbTotalVendas.setForeground(new java.awt.Color(173, 181, 189));
        LbTotalVendas.setText("Total de vendas");

        LbVendasNumero.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        LbVendasNumero.setForeground(new java.awt.Color(255, 255, 255));
        LbVendasNumero.setText("0");

        javax.swing.GroupLayout PanelTotalVendaLayout = new javax.swing.GroupLayout(PanelTotalVenda);
        PanelTotalVenda.setLayout(PanelTotalVendaLayout);
        PanelTotalVendaLayout.setHorizontalGroup(
            PanelTotalVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTotalVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTotalVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbTotalVendas)
                    .addComponent(LbVendasNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        PanelTotalVendaLayout.setVerticalGroup(
            PanelTotalVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTotalVendaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(LbTotalVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbVendasNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        View.standardCornerRadius(PanelDataEBotao);
        PanelDataEBotao.setBackground(new java.awt.Color(255, 255, 255));
        View.standardCornerRadius(PanelDataEBotao);
        PanelDataEBotao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDataFinal.setBackground(new java.awt.Color(248, 249, 250));
        try {
            txtDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataFinal.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        View.standardCornerRadius(txtDataFinal);
        PanelDataEBotao.add(txtDataFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 6, 127, 40));

        txtDataInicial.setBackground(new java.awt.Color(248, 249, 250));
        try {
            txtDataInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataInicial.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        View.standardCornerRadius(txtDataInicial);
        PanelDataEBotao.add(txtDataInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 6, 127, 40));

        jLabel1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel1.setText("A partir de:");
        PanelDataEBotao.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 23, -1, -1));

        jLabel2.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel2.setText("Até:");
        PanelDataEBotao.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 23, -1, -1));

        BtnGerar.setBackground(new java.awt.Color(78, 52, 46));
        BtnGerar.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        BtnGerar.setForeground(new java.awt.Color(255, 255, 255));
        BtnGerar.setText("Gerar");
        View.standardCornerRadius(BtnGerar);
        BtnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGerarActionPerformed(evt);
            }
        });
        PanelDataEBotao.add(BtnGerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 108, 40));

        BtnSalvar.setBackground(new java.awt.Color(78, 52, 46));
        BtnSalvar.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        BtnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalvar.setText("Salvar");
        View.standardCornerRadius(BtnSalvar);
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMainLayout = new javax.swing.GroupLayout(PanelMain);
        PanelMain.setLayout(PanelMainLayout);
        PanelMainLayout.setHorizontalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelMainLayout.createSequentialGroup()
                        .addComponent(PanelReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PanelTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addComponent(PanelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelDataEBotao, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        PanelMainLayout.setVerticalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(PanelDataEBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PanelTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(PanelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Salvar Relatório");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Arquivo de texto (*.txt)", "txt"));
        
        LocalDateTime now = LocalDateTime.now();
        String defaultFileName = String.format("relatorio_%s.txt", 
            now.format(DateTimeFormatter.ofPattern("dd-MM-yyyy_HH-mm")));
        fileChooser.setSelectedFile(new File(defaultFileName));
        
        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            if (!file.getName().toLowerCase().endsWith(".txt")) {
                file = new File(file.getAbsolutePath() + ".txt");
            }
            
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
                writer.write(txtAreaRelatorio.getText());
                JOptionPane.showMessageDialog(this, 
                    "Relatório salvo com sucesso em:\n" + file.getAbsolutePath(),
                    "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this,
                    "Erro ao salvar o arquivo: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void BtnGerarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

            String dataInicialStr = txtDataInicial.getText();
            String dataFinalStr = txtDataFinal.getText();

            LocalDateTime dataInicial = LocalDate.parse(dataInicialStr, formatter).atStartOfDay();
            LocalDateTime dataFinal = LocalDate.parse(dataFinalStr, formatter).atTime(23, 59, 59);

            Relatorio relatorio = new Relatorio();
            relatorio.setGerador(usuario);
            String relatorioTxt = relatorio.gerarRelatorioFormatado(dataInicial, dataFinal);

            txtAreaRelatorio.setText(relatorioTxt);
            LbReceitaNumero.setText(String.format("R$ %.2f", relatorio.getTotalVendas()));
            LbVendasNumero.setText(String.valueOf(relatorio.getQuantidadeVendas()));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao gerar relatório. Verifique se as datas estão no formato correto (dd/mm/aaaa)",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorios(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGerar;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JLabel LbReceitaNumero;
    private javax.swing.JLabel LbReceitaTotal;
    private javax.swing.JLabel LbTotalVendas;
    private javax.swing.JLabel LbVendasNumero;
    private javax.swing.JPanel PanelDataEBotao;
    private javax.swing.JPanel PanelFundo;
    private javax.swing.JPanel PanelMain;
    private javax.swing.JPanel PanelReceita;
    private javax.swing.JPanel PanelTotalVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaRelatorio;
    private javax.swing.JFormattedTextField txtDataFinal;
    private javax.swing.JFormattedTextField txtDataInicial;
    // End of variables declaration//GEN-END:variables

    public void atualizarReceitaTotal() {
        VendaDAO vendaDAO = new VendaDAO();
        double total = vendaDAO.getTotalVendas();

        java.text.NumberFormat currencyFormat = java.text.NumberFormat.getCurrencyInstance();
        LbReceitaNumero.setText(currencyFormat.format(total));
    }
    
    public void atualizarTotalVendas() {
        VendaDAO vendaDAO = new VendaDAO();
        int total = vendaDAO.listarVendas().size();
        

        LbVendasNumero.setText(String.valueOf(total));
    }
}
