/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.bars_register.view;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author limag
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        String path = "/images/Logo-Bars.png";
        int w = 119;
        int h = 160;
        carregarLogo(path, w, h);
    }

    public void carregarLogo(String path, int w, int h) {
        try {
            java.net.URL imageURL = getClass().getResource(path);
            if (imageURL != null) {
                ImageIcon icon = new ImageIcon(imageURL);
                Image img = icon.getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH);
                LbLogo.setIcon(new ImageIcon(img));
            } else {
                System.err.println("Imagem não encontrada: " + path);
            }
        } catch (Exception e) {
            System.err.println("Erro ao carregar a logo: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFundo = new javax.swing.JPanel();
        PanelLogin = new javax.swing.JPanel();
        BtnEntrar = new javax.swing.JButton();
        LbLogo = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        txtLogin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelFundo.setBackground(new java.awt.Color(233, 236, 239));
        PanelFundo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 250, 100));

        PanelLogin.setPreferredSize(new java.awt.Dimension(300, 400));
        PanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnEntrar.setBackground(new java.awt.Color(93, 64, 55));
        BtnEntrar.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        BtnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEntrar.setText("Entrar");
        BtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEntrarActionPerformed(evt);
            }
        });
        PanelLogin.add(BtnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 349, 250, 45));

        LbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbLogo.setPreferredSize(new java.awt.Dimension(119, 160));
        PanelLogin.add(LbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        txtSenha.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        PanelLogin.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 284, 250, 45));

        txtLogin.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        PanelLogin.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 229, 250, 45));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(93, 64, 55));
        jLabel1.setText("Bar's Register");
        PanelLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 176, -1, -1));

        PanelFundo.add(PanelLogin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntrarActionPerformed
        // TODO add your handling code here:
        MainFrame mainframe = new MainFrame();
        mainframe.setVisible(true);
    }//GEN-LAST:event_BtnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEntrar;
    private javax.swing.JLabel LbLogo;
    private javax.swing.JPanel PanelFundo;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
